name: Linux Wheels

on:
  push:
    branches:
      - master
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

# Every time you make a push to your PR, it immediately cancels the previous checks, 
# and start a new one. The other runner will be available more quickly to your PR. 
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # The release tag to pull for building the wheels
  GTSAM_RELEASE_TAG: python-updates

jobs:
  linux-build:
    name: Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp38-cp38", "cp39-cp39", "cp310-cp310", "cp311-cp311"]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 \
        -e PYTHON_VERSION=${{ matrix.pyversion }} \
        -e GTSAM_RELEASE_TAG=$GTSAM_RELEASE_TAG \
        -v `pwd`:/io varunagrawal/gtsam-manylinux:latest /io/build-linux-wheels.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .

    - name: Archive wheels
      uses: actions/upload-artifact@v3
      with:
        name: gtsam-$GTSAM_RELEASE_TAG-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
        path: wheelhouse/gtsam-$GTSAM_RELEASE_TAG-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
