name: Mac Wheels

on:
  push:
    branches:
      - master
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

env:
  # The release tag to pull for building the wheels
  GTSAM_RELEASE_TAG: 4.2.0
  BOOST_VERSION: 1.73.0

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-12", "macos-11"]
        pyversion: ["python@3.8", "python@3.9", "python@3.10", "python@3.11"]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Boost
      run: ./install_boost.sh

    - name: Build the macOS wheels
      run: |
        ./build-macos-wheels.sh ${{ matrix.pyversion }}

    - name: Archive wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-macos-${{ matrix.pyversion }}-${{ matrix.os }}
        path: ./wheelhouse
