name: Linux Wheels

on:
  push:
    branches:
      - master
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  linux-build:
    name: Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp38-cp38", "cp39-cp39", "cp310-cp310", "cp311-cp311"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 -e PYTHON_VERSION=${{ matrix.pyversion }} -v `pwd`:/io varunagrawal/gtsam-manylinux:latest /io/build-wheels-new.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .

    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: gtsam-4.2.0-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
        #TODO(Varun) update this once gtsam PR 1624 is merged
        path: wheelhouse/gtsam-4.2a9-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
