name: Pybind11 CI

on:
  push:
    branches:
      - master
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  linux-build:
    name: Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp36-cp36m", "cp37-cp37m", "cp38-cp38", "cp39-cp39"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 -e PYTHON_VERSION=${{ matrix.pyversion }} -v `pwd`:/io varunagrawal/gtsam-manylinux:latest /io/build-wheels-new.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .

    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: gtsam-4.1.1-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
        path: wheelhouse/gtsam-4.1.1-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
  mac-build:
    name: Wrapper macOS Build
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: ["python@3.8", "python@3.9"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the macOS wheels
      run: |
        ./build-macos-new.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels-macos-${{ matrix.pyversion }}
        path: ./wheelhouse