name: Mac CI

on:
  push:
    branches:
      - master
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", "macos-10.15"]
        pyversion: ["python@3.8", "python@3.9"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the macOS wheels
      run: |
        ./build-macos-new.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels-macos-${{ matrix.pyversion }}-${{ matrix.os }}
        path: ./wheelhouse
